Building com.example.hidoc for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project:
6ACQ282896
Running pod install...                                           1,300ms
Running Xcode build...
Xcode build done.                                            9.2s
Failed to build iOS app
Error (Xcode): No profiles for 'com.example.hidoc' were found: Xcode couldn't find any iOS App
Development provisioning profiles matching 'com.example.hidoc'. Automatic signing is disabled and
unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to
xcodebuild.
/Users/yazer/StudioProjects/hidoc/ios/Runner.xcodeproj



It appears that there was a problem signing your application prior to installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem.
Encountered error while building for device.
